import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Montserrat } from "next/font/google";
import Footer from "./components/Footer";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  display: "swap",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable}  ${geistMono.variable} scroll-smooth antialiased`}
      >
        {children}
           {/* Subtle Bottom Blur */}
           <Footer/>
       <div
  className="pointer-events-none fixed bottom-0 left-0 w-full h-40 z-[999] backdrop-blur-xl"
  style={{
    WebkitMaskImage: 'linear-gradient(to top, black, transparent)',
    maskImage: 'linear-gradient(to top, black, transparent)',
    WebkitMaskRepeat: 'no-repeat',
    maskRepeat: 'no-repeat',
  }}
/>




      </body>
    </html>
  );
}
